version: '3.8'

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.99.0.0/16

services:
  catalogo-service:
    build: ./catalogo-service
    container_name: catalogo-tom-hanks-yago # Nome único
    restart: always
    ports:
      - "8228:3000"
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - TMDB_API_KEY=${TMDB_API_KEY}
      - DB_HOST=35.226.64.52
      - DB_USER=IAC_2026_02_yago_martins
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=IAC_2026_02_yago_martins
      - DB_PORT=3306
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - app-network
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    image: auth-yago-v2
    container_name: auth-service-yago
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    networks:
      - app-network